### ISSUE TITLE
@import "Pattern"; doesn't work

### ISSUE THREAD

**Issue by Dangoo** [sinnerschrader/patternplate-transform-postcss#1]
### Input
```css
/* index.css */
:root {
  --background-color: #f00;
}
```

```css
/* demo.css */
@import "Pattern";

.bar {
  background-color: var(--background-color);
}
```

### Actual
A `demo.css` file with an `@import "Pattern";` statement fails with the error message
```
Error in "globals/colors" during transform "postcss" of "<root>/patterns/globals/colors/demo.css": Cannot find module 'Pattern'`
```

### Expected
A `demo.css` file with an `@import "Pattern";` resolves to `index.css`

### Notes
When removing `@import "Pattern";`
The error message says:
```
Error in "globals/colors" during transform "postcss" of "<root>/patterns/globals/colors/demo.css": Cannot read property 'indexOf' of undefined
```
